### ISSUE TITLE
I encountered two problems while running training😭

### ISSUE THREAD

**Issue by alexandsunny** [wkcn/TinyCLIP#2] opened 2024-03-29 07:55 UTC
Question 1
I used type webdataset data and the following error occurred. I changed dataloader.batch_size to args.batch_size and I was able to continue running. Will this affect the results?
File "/mnt/public/usr/bolao/project/tinyclip/src/training/train.py", line 141, in train_one_epoch
    batch_size = dataloader.batch_size
AttributeError: 'WebLoader' object has no attribute 'batch_size'

Question 2
After solving Question 1, I continued running and found Question 2. The gpu memory was increasing when running each batch, which eventually caused the gpu memory to explode.
Traceback (most recent call last):
  File "src/training/main.py", line 567, in <module>
    main()
  File "src/training/main.py", line 536, in main
    rtn = train_one_epoch(model, data, epoch, optimizer, scaler,
  File "/mnt/public/usr/bolao/project/tinyclip/src/training/train.py", line 461, in train_one_epoch
    total_loss = grad_cache(
  File "/mnt/public/usr/bolao/project/tinyclip/src/training/train.py", line 314, in naive_model_fn
    scaler.scale(loss).backward()
  File "/opt/conda/lib/python3.8/site-packages/torch/_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 39.39 GiB total capacity; 38.18 GiB already allocated; 12.88 MiB free; 38.24 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by wkcn** [comment] 2024-04-01 05:39
@alexandsunny 

Thanks for your attention to our work!

1. You can replace L141 with `batch_size = args.batch_size`.
2. Did you add the argument `--grad-checkpointing`?

In our experiments, the number of GPUs (32GB memory) is 32 and the batch size per GPU is 1024. If the number of GPUs is less than 32, [grad cache](https://github.com/luyug/GradCache) should be enabled. I did not release the part of grad cache yet.

**Comment by alexandsunny** [comment] 2024-04-01 08:50
> @alexandsunny
> 
> Thanks for your attention to our work!
> 
> 1. You can replace L141 with `batch_size = args.batch_size`.
> 2. Did you add the argument `--grad-checkpointing`?
> 
> In our experiments, the number of GPUs (32GB memory) is 32 and the batch size per GPU is 1024. If the number of GPUs is less than 32, [grad cache](https://github.com/luyug/GradCache) should be enabled. I did not release the part of grad cache yet.

When I was debugging the program, I only used one A100 (40GB), the batch size per GPU was 16, and I added "--grad-checkpointing". 
I logged and found that the training memory of each batch was increasing until it exceeded the memory.
I just tried removing "--grad-checkpointing" and I was able to continue training.🙏

**Comment by wkcn** [comment] 2024-04-01 10:31
@alexandsunny Thanks for pointing it out! It seems to be a bug of TinyCLIP or PyTorch.

**Comment by alexandsunny** [comment] 2024-04-02 06:29
> @alexandsunny Thanks for pointing it out! It seems to be a bug of TinyCLIP or PyTorch.

Will this problem be fixed in the future?🤔️

**Comment by wkcn** [comment] 2024-04-02 06:42
@alexandsunny Which version of PyTorch did you use? I need to reproduce the problem. You can try to upgrade PyTorch.

**Comment by alexandsunny** [comment] 2024-04-02 09:33
> @alexandsunny Which version of PyTorch did you use? I need to reproduce the problem. You can try to upgrade PyTorch.

I tried it on two torch environments
 1.13.0a0+340c412
 1.12.0a0+2c916ef
I will try to upgrade torch to a higher version in the next few days and give it a try

**Comment by loserking111** [comment] 2024-06-25 07:40
I want to replace the clip model weights with Tinyclip model weights to initialize, how should I change the network architecture?

**Comment by wkcn** [comment] 2024-06-25 11:39
Close it. Feel free to re-open it if the issue still exists.

**Closed as completed by wkcn** 2024-06-25 11:39 UTC
